name: E2e testing

on:
  # faz o dispatch automático
  workflow_dispatch:
  push:
    branches: [$default-branch]
  pull_request:
    branches: [$default-branch]

jobs:
  cypress:
    defaults:
      run:
        working-directory: dashboard

    runs-on: ubuntu-latest
    timeout-minutes: 15 # timeout maior

    steps:
      - uses: actions/checkout@v2
      - run: npm install
      
      # roda um build com env de production
      - run: npm run build
        env:
          NODE_ENV: production

      # para que eu possa rodar o teste localmente
      - name: Run project locally
        run: |
          npm install serve
          $(npm bin)/serve dist -s -p 8080 &

      - name: Run tests
        uses: cypress-io/github-action@v2
        with:
          working-directory: dashboard
          browser: chrome
          headless: true # não abre browser nenhum
